package com.tritiumgaming.shared.core.common.network

enum class FirebaseFunctionError(val code: Int) {
    UNSUPPORTED_VERSION(1000),
    AUTH_REQUIRED_PREFERENCES(1001),
    INTERNAL_ERROR_MARKETPLACE_STATE(1002),
    AUTH_REQUIRED_PURCHASE(1003),
    INVALID_ITEM_TYPE(1004),
    INTERNAL_ERROR_PURCHASE(1005),
    ITEM_NOT_FOUND(1006),
    INSUFFICIENT_CREDITS(1007),
    BUNDLE_NOT_FOUND(1008),
    BUNDLE_NO_ITEMS(1009),
    BUNDLE_ALREADY_UNLOCKED(1010),
    INTERNAL_ERROR_FETCH_TYPOGRAPHIES(1011),
    INTERNAL_ERROR_FETCH_PALETTES(1012),
    INTERNAL_ERROR_FETCH_BUNDLES(1013),
    AUTH_REQUIRED_ADD_CREDITS(1014),
    INVALID_CREDIT_AMOUNT(1015),
    INTERNAL_ERROR_ADD_CREDITS(1016),
    UNKNOWN(-1);
}
