package com.tritiumgaming.phasmophobiaevidencepicker.operation.domain.journal.mapper

//TODO(Create all enum values)
class GhostResources {

    enum class GhostTitle {
        BANSHEE,
        DEMON,
        DEOGEN,
        GORYO,
        HANTU,
        JINN,
        MARE,
        MOROI,
        MYLING,
        OBAKE,
        ONI,
        ONRYO,
        PHANTOM,
        POLTERGEIST,
        RAIJU,
        REVENANT,
        SHADE,
        SPIRIT,
        THAYE,
        THE_TWINS,
        THE_MIMIC,
        WRAITH,
        YOKAI,
        YUREI
    }

    enum class GhostDescription {
        BANSHEE,
        DEMON,
        DEOGEN,
        GORYO,
        HANTU,
        JINN,
        MARE,
        MOROI,
        MYLING,
        OBAKE,
        ONI,
        ONRYO,
        PHANTOM,
        POLTERGEIST,
        RAIJU,
        REVENANT,
        SHADE,
        SPIRIT,
        THAYE,
        THE_TWINS,
        THE_MIMIC,
        WRAITH,
        YOKAI,
        YUREI
    }

    enum class GhostStrength {
        BANSHEE,
        DEMON,
        DEOGEN,
        GORYO,
        HANTU,
        JINN,
        MARE,
        MOROI,
        MYLING,
        OBAKE,
        ONI,
        ONRYO,
        PHANTOM,
        POLTERGEIST,
        RAIJU,
        REVENANT,
        SHADE,
        SPIRIT,
        THAYE,
        THE_TWINS,
        THE_MIMIC,
        WRAITH,
        YOKAI,
        YUREI
    }

    enum class GhostWeakness {
        BANSHEE,
        DEMON,
        DEOGEN,
        GORYO,
        HANTU,
        JINN,
        MARE,
        MOROI,
        MYLING,
        OBAKE,
        ONI,
        ONRYO,
        PHANTOM,
        POLTERGEIST,
        RAIJU,
        REVENANT,
        SHADE,
        SPIRIT,
        THAYE,
        THE_TWINS,
        THE_MIMIC,
        WRAITH,
        YOKAI,
        YUREI
    }

    enum class GhostHuntInfo {
        BANSHEE,
        DEMON,
        DEOGEN,
        GORYO,
        HANTU,
        JINN,
        MARE,
        MOROI,
        MYLING,
        OBAKE,
        ONI,
        ONRYO,
        PHANTOM,
        POLTERGEIST,
        RAIJU,
        REVENANT,
        SHADE,
        SPIRIT,
        THAYE,
        THE_TWINS,
        THE_MIMIC,
        WRAITH,
        YOKAI,
        YUREI
    }

}