package com.tritiumgaming.phasmophobiaevidencepicker.operation.domain.map.simple.mappers

class SimpleMapResources {

    enum class MapTitle {
        SUNNY_MEADOWS,
        SUNNY_MEADOWS_RESTRICTED,
        POINT_HOPE,
        CAMP_WOODWIND,
        CAMP_MAPLE,
        BLEASDALE_FARMHOUSE,
        GRAFTON_FARMHOUSE,
        BROWNSTONE_HIGHSCHOOL,
        EDGEFIELD,
        TANGLEWOOD,
        WILLOW,
        RIDGEVIEW,
        PRISON
    }

    enum class MapThumbnail {
        SUNNY_MEADOWS,
        SUNNY_MEADOWS_RESTRICTED,
        POINT_HOPE,
        CAMP_WOODWIND,
        CAMP_MAPLE,
        BLEASDALE_FARMHOUSE,
        GRAFTON_FARMHOUSE,
        BROWNSTONE_HIGHSCHOOL,
        EDGEFIELD,
        TANGLEWOOD,
        WILLOW,
        RIDGEVIEW,
        PRISON
    }

    enum class MapFloorTitle {
        BASEMENT,
        GROUND_FLOOR,
        FIRST_FLOOR,
        SECOND_FLOOR,
        THIRD_FLOOR,
        FOURTH_FLOOR,
        FIFTH_FLOOR,
        SIXTH_FLOOR,
        SEVENTH_FLOOR,
        EIGHTH_FLOOR,
        NINTH_FLOOR,
        TENTH_FLOOR,
        ATTIC
    }

    enum class MapFloorImage {
        SUNNY_MEADOWS_BASEMENT,
        SUNNY_MEADOWS_FIRST_FLOOR,
        SUNNY_MEADOWS_RESTRICTED_BASEMENT,
        SUNNY_MEADOWS_RESTRICTED_FIRST_FLOOR,
        POINT_HOPE_GROUND_FLOOR,
        POINT_HOPE_SECOND_FLOOR,
        POINT_HOPE_THIRD_FLOOR,
        POINT_HOPE_FOURTH_FLOOR,
        POINT_HOPE_FIFTH_FLOOR,
        POINT_HOPE_SIXTH_FLOOR,
        POINT_HOPE_SEVENTH_FLOOR,
        POINT_HOPE_EIGHTH_FLOOR,
        POINT_HOPE_NINTH_FLOOR,
        POINT_HOPE_TENTH_FLOOR,
        CAMP_WOODWIND_GROUND_FLOOR,
        CAMP_MAPLE_BASEMENT,
        CAMP_MAPLE_FIRST_FLOOR,
        CAMP_MAPLE_SECOND_FLOOR,
        BLEASDALE_FARMHOUSE_FIRST_FLOOR,
        BLEASDALE_FARMHOUSE_SECOND_FLOOR,
        BLEASDALE_FARMHOUSE_ATTIC,
        GRAFTON_FARMHOUSE_FIRST_FLOOR,
        GRAFTON_FARMHOUSE_SECOND_FLOOR,
        GRAFTON_FARMHOUSE_THIRD_FLOOR,
        BROWNSTONE_HIGHSCHOOL_FIRST_FLOOR,
        BROWNSTONE_HIGHSCHOOL_SECOND_FLOOR,
        EDGEFIELD_BASEMENT,
        EDGEFIELD_FIRST_FLOOR,
        EDGEFIELD_SECOND_FLOOR,
        TANGLEWOOD_BASEMENT,
        TANGLEWOOD_FIRST_FLOOR,
        WILLOW_BASEMENT,
        WILLOW_FIRST_FLOOR,
        RIDGEVIEW_BASEMENT,
        RIDGEVIEW_FIRST_FLOOR,
        RIDGEVIEW_SECOND_FLOOR,
        PRISON_FIRST_FLOOR,
        PRISON_SECOND_FLOOR
    }

    enum class MapTitleLength {
        ABBREVIATED,
        FULL
    }

}