package com.tritiumgaming.feature.operation.app.mappers

import androidx.annotation.DrawableRes
import androidx.annotation.StringRes
import com.tritiumgaming.core.resources.R
import com.tritiumgaming.shared.operation.domain.codex.mappers.CodexAchievementsResources.AchievementContent
import com.tritiumgaming.shared.operation.domain.codex.mappers.CodexAchievementsResources.AchievementIcon
import com.tritiumgaming.shared.operation.domain.codex.mappers.CodexAchievementsResources.AchievementTitle

@StringRes fun AchievementTitle.toStringResource(): Int =
    when (this) {
        AchievementTitle.TRAINING_WHEELS -> R.string.achievements_trainingwheels_name
        AchievementTitle.ROOKIE -> R.string.achievements_rookie_name
        AchievementTitle.PROFESSIONAL -> R.string.achievements_professional_name
        AchievementTitle.BOSS -> R.string.achievements_boss_name
        AchievementTitle.EXTRA_MILE -> R.string.achievements_extramile_name
        AchievementTitle.DEDICATED -> R.string.achievements_dedicated_name
        AchievementTitle.DEVOTED -> R.string.achievements_devoted_name
        AchievementTitle.CHALLENGER -> R.string.achievements_challenger_name
        AchievementTitle.RISE_CHALLENGE -> R.string.achievements_risechallenge_name
        AchievementTitle.TAKE_CHALLENGES -> R.string.achievements_takingchallenges_name
        AchievementTitle.CHUMP_CHANGE -> R.string.achievements_chumpchange_name
        AchievementTitle.FAT_STOCK -> R.string.achievements_fatstock_name
        AchievementTitle.CASH_COW -> R.string.achievements_cashcow_name
        AchievementTitle.BREAK_THE_BANK -> R.string.achievements_breakthebank_name
        AchievementTitle.BARE_ESSENTIALS -> R.string.achievements_bareessentials_name
        AchievementTitle.TOOLS_OF_THE_TRADE -> R.string.achievements_toolsofthetrade_name
        AchievementTitle.FULLY_LOADED -> R.string.achievements_fullyloaded_name
        AchievementTitle.DIRECTOR -> R.string.achievements_director_name
        AchievementTitle.BRONZE_HUNTER -> R.string.achievements_bronzehunter_name
        AchievementTitle.SILVER_HUNTER -> R.string.achievements_silverhunter_name
        AchievementTitle.GOLD_HUNTER -> R.string.achievements_goldhunter_name
        AchievementTitle.BANSHEE -> R.string.achievements_banshee_name
        AchievementTitle.DEMON -> R.string.achievements_demon_name
        AchievementTitle.DEOGEN -> R.string.achievements_deogen_name
        AchievementTitle.GORYO -> R.string.achievements_goryo_name
        AchievementTitle.HANTU -> R.string.achievements_hantu_name
        AchievementTitle.JINN -> R.string.achievements_jinn_name
        AchievementTitle.MARE -> R.string.achievements_mare_name
        AchievementTitle.MOROI -> R.string.achievements_moroi_name
        AchievementTitle.MYLING -> R.string.achievements_myling_name
        AchievementTitle.OBAKE -> R.string.achievements_obake_name
        AchievementTitle.ONI -> R.string.achievements_oni_name
        AchievementTitle.ONRYO -> R.string.achievements_onryo_name
        AchievementTitle.PHANTOM -> R.string.achievements_phantom_name
        AchievementTitle.POLTERGEIST -> R.string.achievements_poltergeist_name
        AchievementTitle.RAIJU -> R.string.achievements_raiju_name
        AchievementTitle.REVENANT -> R.string.achievements_revenant_name
        AchievementTitle.SHADE -> R.string.achievements_shade_name
        AchievementTitle.SPIRIT -> R.string.achievements_spirit_name
        AchievementTitle.THAYE -> R.string.achievements_thaye_name
        AchievementTitle.MIMIC -> R.string.achievements_mimic_name
        AchievementTitle.TWINS -> R.string.achievements_twins_name
        AchievementTitle.WRAITH -> R.string.achievements_wraith_name
        AchievementTitle.YOKAI -> R.string.achievements_yokai_name
        AchievementTitle.YUREI -> R.string.achievements_yurei_name
        AchievementTitle.PRESTIGE1 -> R.string.achievements_prestige1_name
        AchievementTitle.PRESTIGE2 -> R.string.achievements_prestige2_name
        AchievementTitle.PRESTIGE3 -> R.string.achievements_prestige3_name
        AchievementTitle.WORK_EXPERIENCE -> R.string.achievements_workexperience_name
        AchievementTitle.FLAWLESS_EXECUTION -> R.string.achievements_flawlessexecution_name
        AchievementTitle.THEYRE_HERE -> R.string.achievements_theyrehere_name
        AchievementTitle.ESCAPE_ARTIST -> R.string.achievements_escapeartist_name
        AchievementTitle.BAIT -> R.string.achievements_bait_name
        AchievementTitle.DOOM_SLAYED -> R.string.achievements_doomslayed_name
    }

@StringRes fun AchievementContent.toStringResource(): Int =
    when (this) {
        AchievementContent.TRAINING_WHEELS -> R.string.achievements_trainingwheels_info
        AchievementContent.ROOKIE -> R.string.achievements_rookie_info
        AchievementContent.PROFESSIONAL -> R.string.achievements_professional_info
        AchievementContent.BOSS -> R.string.achievements_boss_info
        AchievementContent.EXTRA_MILE -> R.string.achievements_extramile_info
        AchievementContent.DEDICATED -> R.string.achievements_dedicated_info
        AchievementContent.DEVOTED -> R.string.achievements_devoted_info
        AchievementContent.CHALLENGER -> R.string.achievements_challenger_info
        AchievementContent.RISE_CHALLENGE -> R.string.achievements_risechallenge_info
        AchievementContent.TAKE_CHALLENGES -> R.string.achievements_takingchallenges_info
        AchievementContent.CHUMP_CHANGE -> R.string.achievements_chumpchange_info
        AchievementContent.FAT_STOCK -> R.string.achievements_fatstock_info
        AchievementContent.CASH_COW -> R.string.achievements_cashcow_info
        AchievementContent.BREAK_THE_BANK -> R.string.achievements_breakthebank_info
        AchievementContent.BARE_ESSENTIALS -> R.string.achievements_bareessentials_info
        AchievementContent.TOOLS_OF_THE_TRADE -> R.string.achievements_toolsofthetrade_info
        AchievementContent.FULLY_LOADED -> R.string.achievements_fullyloaded_info
        AchievementContent.DIRECTOR -> R.string.achievements_director_info
        AchievementContent.BRONZE_HUNTER -> R.string.achievements_bronzehunter_info
        AchievementContent.SILVER_HUNTER -> R.string.achievements_silverhunter_info
        AchievementContent.GOLD_HUNTER -> R.string.achievements_goldhunter_info
        AchievementContent.BANSHEE -> R.string.achievements_banshee_info
        AchievementContent.DEMON -> R.string.achievements_demon_info
        AchievementContent.DEOGEN -> R.string.achievements_deogen_info
        AchievementContent.GORYO -> R.string.achievements_goryo_info
        AchievementContent.HANTU -> R.string.achievements_hantu_info
        AchievementContent.JINN -> R.string.achievements_jinn_info
        AchievementContent.MARE -> R.string.achievements_mare_info
        AchievementContent.MOROI -> R.string.achievements_moroi_info
        AchievementContent.MYLING -> R.string.achievements_myling_info
        AchievementContent.OBAKE -> R.string.achievements_obake_info
        AchievementContent.ONI -> R.string.achievements_oni_info
        AchievementContent.ONRYO -> R.string.achievements_onryo_info
        AchievementContent.PHANTOM -> R.string.achievements_phantom_info
        AchievementContent.POLTERGEIST -> R.string.achievements_poltergeist_info
        AchievementContent.RAIJU -> R.string.achievements_raiju_info
        AchievementContent.REVENANT -> R.string.achievements_revenant_info
        AchievementContent.SHADE -> R.string.achievements_shade_info
        AchievementContent.SPIRIT -> R.string.achievements_spirit_info
        AchievementContent.THAYE -> R.string.achievements_thaye_info
        AchievementContent.MIMIC -> R.string.achievements_mimic_info
        AchievementContent.TWINS -> R.string.achievements_twins_info
        AchievementContent.WRAITH -> R.string.achievements_wraith_info
        AchievementContent.YOKAI -> R.string.achievements_yokai_info
        AchievementContent.YUREI -> R.string.achievements_yurei_info
        AchievementContent.PRESTIGE1 -> R.string.achievements_prestige1_info
        AchievementContent.PRESTIGE2 -> R.string.achievements_prestige2_info
        AchievementContent.PRESTIGE3 -> R.string.achievements_prestige3_info
        AchievementContent.WORK_EXPERIENCE -> R.string.achievements_workexperience_info
        AchievementContent.FLAWLESS_EXECUTION -> R.string.achievements_flawlessexecution_info
        AchievementContent.THEYRE_HERE -> R.string.achievements_theyrehere_info
        AchievementContent.ESCAPE_ARTIST -> R.string.achievements_escapeartist_info
        AchievementContent.BAIT -> R.string.achievements_bait_info
        AchievementContent.DOOM_SLAYED -> R.string.achievements_doomslayed_info
    }

@DrawableRes fun AchievementIcon.toDrawableResource(): Int =
    when (this) {
        AchievementIcon.TRAINING_WHEELS -> R.drawable.ic_achievement_banshee
        AchievementIcon.ROOKIE -> R.drawable.ic_achievement_banshee
        AchievementIcon.PROFESSIONAL -> R.drawable.ic_achievement_banshee
        AchievementIcon.BOSS -> R.drawable.ic_achievement_banshee
        AchievementIcon.EXTRA_MILE -> R.drawable.ic_achievement_banshee
        AchievementIcon.DEDICATED -> R.drawable.ic_achievement_banshee
        AchievementIcon.DEVOTED -> R.drawable.ic_achievement_banshee
        AchievementIcon.CHALLENGER -> R.drawable.ic_achievement_banshee
        AchievementIcon.RISE_CHALLENGE -> R.drawable.ic_achievement_banshee
        AchievementIcon.TAKE_CHALLENGES -> R.drawable.ic_achievement_banshee
        AchievementIcon.CHUMP_CHANGE -> R.drawable.ic_achievement_banshee
        AchievementIcon.FAT_STOCK -> R.drawable.ic_achievement_banshee
        AchievementIcon.CASH_COW -> R.drawable.ic_achievement_banshee
        AchievementIcon.BREAK_THE_BANK -> R.drawable.ic_achievement_banshee
        AchievementIcon.BARE_ESSENTIALS -> R.drawable.ic_achievement_banshee
        AchievementIcon.TOOLS_OF_THE_TRADE -> R.drawable.ic_achievement_banshee
        AchievementIcon.FULLY_LOADED -> R.drawable.ic_achievement_banshee
        AchievementIcon.DIRECTOR -> R.drawable.ic_achievement_banshee
        AchievementIcon.BRONZE_HUNTER -> R.drawable.ic_achievement_banshee
        AchievementIcon.SILVER_HUNTER -> R.drawable.ic_achievement_banshee
        AchievementIcon.GOLD_HUNTER -> R.drawable.ic_achievement_banshee
        AchievementIcon.BANSHEE -> R.drawable.ic_achievement_banshee
        AchievementIcon.DEMON -> R.drawable.ic_achievement_banshee
        AchievementIcon.DEOGEN -> R.drawable.ic_achievement_banshee
        AchievementIcon.GORYO -> R.drawable.ic_achievement_banshee
        AchievementIcon.HANTU -> R.drawable.ic_achievement_banshee
        AchievementIcon.JINN -> R.drawable.ic_achievement_banshee
        AchievementIcon.MARE -> R.drawable.ic_achievement_banshee
        AchievementIcon.MOROI -> R.drawable.ic_achievement_banshee
        AchievementIcon.MYLING -> R.drawable.ic_achievement_banshee
        AchievementIcon.OBAKE -> R.drawable.ic_achievement_banshee
        AchievementIcon.ONI -> R.drawable.ic_achievement_banshee
        AchievementIcon.ONRYO -> R.drawable.ic_achievement_banshee
        AchievementIcon.PHANTOM -> R.drawable.ic_achievement_banshee
        AchievementIcon.POLTERGEIST -> R.drawable.ic_achievement_banshee
        AchievementIcon.RAIJU -> R.drawable.ic_achievement_banshee
        AchievementIcon.REVENANT -> R.drawable.ic_achievement_banshee
        AchievementIcon.SHADE -> R.drawable.ic_achievement_banshee
        AchievementIcon.SPIRIT -> R.drawable.ic_achievement_banshee
        AchievementIcon.THAYE -> R.drawable.ic_achievement_banshee
        AchievementIcon.MIMIC -> R.drawable.ic_achievement_banshee
        AchievementIcon.TWINS -> R.drawable.ic_achievement_banshee
        AchievementIcon.WRAITH -> R.drawable.ic_achievement_banshee
        AchievementIcon.YOKAI -> R.drawable.ic_achievement_banshee
        AchievementIcon.YUREI -> R.drawable.ic_achievement_banshee
        AchievementIcon.PRESTIGE1 -> R.drawable.ic_achievement_banshee
        AchievementIcon.PRESTIGE2 -> R.drawable.ic_achievement_banshee
        AchievementIcon.PRESTIGE3 -> R.drawable.ic_achievement_banshee
        AchievementIcon.WORK_EXPERIENCE -> R.drawable.ic_achievement_banshee
        AchievementIcon.FLAWLESS_EXECUTION -> R.drawable.ic_achievement_banshee
        AchievementIcon.THEYRE_HERE -> R.drawable.ic_achievement_banshee
        AchievementIcon.ESCAPE_ARTIST -> R.drawable.ic_achievement_banshee
        AchievementIcon.BAIT -> R.drawable.ic_achievement_banshee
        AchievementIcon.DOOM_SLAYED -> R.drawable.ic_achievement_banshee
        // TODO Replace ic_achievement_banshee with correct icon
        /*AchievementIcon.TRAINING_WHEELS -> R.drawable.ic_achievement_trainingwheels
        AchievementIcon.ROOKIE -> R.drawable.ic_achievement_rookie
        AchievementIcon.PROFESSIONAL -> R.drawable.ic_achievement_professional
        AchievementIcon.BOSS -> R.drawable.ic_achievement_boss
        AchievementIcon.EXTRA_MILE -> R.drawable.ic_achievement_extramile
        AchievementIcon.DEDICATED -> R.drawable.ic_achievement_dedicated
        AchievementIcon.DEVOTED -> R.drawable.ic_achievement_devoted
        AchievementIcon.CHALLENGER -> R.drawable.ic_achievement_challenger
        AchievementIcon.RISE_CHALLENGE -> R.drawable.ic_achievement_risechallenge
        AchievementIcon.TAKE_CHALLENGES -> R.drawable.ic_achievement_takingchallenges
        AchievementIcon.CHUMP_CHANGE -> R.drawable.ic_achievement_chumpchange
        AchievementIcon.FAT_STOCK -> R.drawable.ic_achievement_fatstock
        AchievementIcon.CASH_COW -> R.drawable.ic_achievement_cashcow
        AchievementIcon.BREAK_THE_BANK -> R.drawable.ic_achievement_breakthebank
        AchievementIcon.BARE_ESSENTIALS -> R.drawable.ic_achievement_bareessentials
        AchievementIcon.TOOLS_OF_THE_TRADE -> R.drawable.ic_achievement_toolsofthetrade
        AchievementIcon.FULLY_LOADED -> R.drawable.ic_achievement_fullyloaded
        AchievementIcon.DIRECTOR -> R.drawable.ic_achievement_director
        AchievementIcon.BRONZE_HUNTER -> R.drawable.ic_achievement_bronzehunter
        AchievementIcon.SILVER_HUNTER -> R.drawable.ic_achievement_silverhunter
        AchievementIcon.GOLD_HUNTER -> R.drawable.ic_achievement_goldhunter
        AchievementIcon.BANSHEE -> R.drawable.ic_achievement_banshee
        AchievementIcon.DEMON -> R.drawable.ic_achievement_demon
        AchievementIcon.DEOGEN -> R.drawable.ic_achievement_deogen
        AchievementIcon.GORYO -> R.drawable.ic_achievement_goryo
        AchievementIcon.HANTU -> R.drawable.ic_achievement_hantu
        AchievementIcon.JINN -> R.drawable.ic_achievement_jinn
        AchievementIcon.MARE -> R.drawable.ic_achievement_mare
        AchievementIcon.MOROI -> R.drawable.ic_achievement_moroi
        AchievementIcon.MYLING -> R.drawable.ic_achievement_myling
        AchievementIcon.OBAKE -> R.drawable.ic_achievement_obake
        AchievementIcon.ONI -> R.drawable.ic_achievement_oni
        AchievementIcon.ONRYO -> R.drawable.ic_achievement_onryo
        AchievementIcon.PHANTOM -> R.drawable.ic_achievement_phantom
        AchievementIcon.POLTERGEIST -> R.drawable.ic_achievement_poltergeist
        AchievementIcon.RAIJU -> R.drawable.ic_achievement_raiju
        AchievementIcon.REVENANT -> R.drawable.ic_achievement_revenant
        AchievementIcon.SHADE -> R.drawable.ic_achievement_shade
        AchievementIcon.SPIRIT -> R.drawable.ic_achievement_spirit
        AchievementIcon.THAYE -> R.drawable.ic_achievement_thaye
        AchievementIcon.MIMIC -> R.drawable.ic_achievement_mimic
        AchievementIcon.TWINS -> R.drawable.ic_achievement_twins
        AchievementIcon.WRAITH -> R.drawable.ic_achievement_wraith
        AchievementIcon.YOKAI -> R.drawable.ic_achievement_yokai
        AchievementIcon.YUREI -> R.drawable.ic_achievement_yurei
        AchievementIcon.PRESTIGE1 -> R.drawable.ic_achievement_prestige1
        AchievementIcon.PRESTIGE2 -> R.drawable.ic_achievement_prestige2
        AchievementIcon.PRESTIGE3 -> R.drawable.ic_achievement_prestige3
        AchievementIcon.WORK_EXPERIENCE -> R.drawable.ic_achievement_workexperience
        AchievementIcon.FLAWLESS_EXECUTION -> R.drawable.ic_achievement_flawlessexecution
        AchievementIcon.THEYRE_HERE -> R.drawable.ic_achievement_theyrehere
        AchievementIcon.ESCAPE_ARTIST -> R.drawable.ic_achievement_escapeartist
        AchievementIcon.BAIT -> R.drawable.ic_achievement_bait
        AchievementIcon.DOOM_SLAYED -> R.drawable.ic_achievement_doomslayed*/
    }
