package com.tritiumgaming.phasmophobiaevidencepicker.operation.presentation.app.mappers

import androidx.annotation.StringRes
import com.tritiumgaming.phasmophobiaevidencepicker.R
import com.tritiumgaming.phasmophobiaevidencepicker.operation.domain.ghostname.mappers.GhostNameResources

@StringRes fun GhostNameResources.Name.toStringResource(): Int =
    when (this) {
        GhostNameResources.Name.ALEX -> R.string.ghost_name_alex
        GhostNameResources.Name.AMIT -> R.string.ghost_name_amit
        GhostNameResources.Name.ANDREW -> R.string.ghost_name_andrew
        GhostNameResources.Name.ANN -> R.string.ghost_name_ann
        GhostNameResources.Name.ANTHONY -> R.string.ghost_name_anthony
        GhostNameResources.Name.APRIL -> R.string.ghost_name_april
        GhostNameResources.Name.BARBARA -> R.string.ghost_name_barbara
        GhostNameResources.Name.BECKY -> R.string.ghost_name_becky
        GhostNameResources.Name.BENJAMIN -> R.string.ghost_name_benjamin
        GhostNameResources.Name.BETTY -> R.string.ghost_name_betty
        GhostNameResources.Name.BILLY -> R.string.ghost_name_billy
        GhostNameResources.Name.BORRIS -> R.string.ghost_name_borris
        GhostNameResources.Name.BRADLEY -> R.string.ghost_name_bradley
        GhostNameResources.Name.BRENDEN -> R.string.ghost_name_brenden
        GhostNameResources.Name.BRIAN -> R.string.ghost_name_brian
        GhostNameResources.Name.CARLA -> R.string.ghost_name_carla
        GhostNameResources.Name.CARLOS -> R.string.ghost_name_carlos
        GhostNameResources.Name.CAROL -> R.string.ghost_name_carol
        GhostNameResources.Name.CATHERINE -> R.string.ghost_name_catherine
        GhostNameResources.Name.CATIANA -> R.string.ghost_name_catiana
        GhostNameResources.Name.CHARLES -> R.string.ghost_name_charles
        GhostNameResources.Name.CHRISTOPHER -> R.string.ghost_name_christopher
        GhostNameResources.Name.CORA -> R.string.ghost_name_cora
        GhostNameResources.Name.COREY -> R.string.ghost_name_corey
        GhostNameResources.Name.DANIEL -> R.string.ghost_name_daniel
        GhostNameResources.Name.DAVE -> R.string.ghost_name_dave
        GhostNameResources.Name.DAVID -> R.string.ghost_name_david
        GhostNameResources.Name.DONALD -> R.string.ghost_name_donald
        GhostNameResources.Name.DONNA -> R.string.ghost_name_donna
        GhostNameResources.Name.DORIS -> R.string.ghost_name_doris
        GhostNameResources.Name.DOROTHY -> R.string.ghost_name_dorothy
        GhostNameResources.Name.EDIE -> R.string.ghost_name_edie
        GhostNameResources.Name.EDWARD -> R.string.ghost_name_edward
        GhostNameResources.Name.ELIZABETH -> R.string.ghost_name_elizabeth
        GhostNameResources.Name.ELLA -> R.string.ghost_name_ella
        GhostNameResources.Name.ELLEN -> R.string.ghost_name_ellen
        GhostNameResources.Name.EMILY -> R.string.ghost_name_emily
        GhostNameResources.Name.EMMA -> R.string.ghost_name_emma
        GhostNameResources.Name.ERIC -> R.string.ghost_name_eric
        GhostNameResources.Name.EVA -> R.string.ghost_name_eva
        GhostNameResources.Name.GARY -> R.string.ghost_name_gary
        GhostNameResources.Name.GEORGE -> R.string.ghost_name_george
        GhostNameResources.Name.GEORGIA -> R.string.ghost_name_georgia
        GhostNameResources.Name.GLORIA -> R.string.ghost_name_gloria
        GhostNameResources.Name.GRANT -> R.string.ghost_name_grant
        GhostNameResources.Name.GREGORY -> R.string.ghost_name_gregory
        GhostNameResources.Name.HAROLD -> R.string.ghost_name_harold
        GhostNameResources.Name.HEATHER -> R.string.ghost_name_heather
        GhostNameResources.Name.HELEN -> R.string.ghost_name_helen
        GhostNameResources.Name.HOLLY -> R.string.ghost_name_holly
        GhostNameResources.Name.HUGO -> R.string.ghost_name_hugo
        GhostNameResources.Name.JACK -> R.string.ghost_name_jack
        GhostNameResources.Name.JAMES -> R.string.ghost_name_james
        GhostNameResources.Name.JAN -> R.string.ghost_name_jan
        GhostNameResources.Name.JANE -> R.string.ghost_name_jane
        GhostNameResources.Name.JASON -> R.string.ghost_name_jason
        GhostNameResources.Name.JAY -> R.string.ghost_name_jay
        GhostNameResources.Name.JAZZ -> R.string.ghost_name_jazz
        GhostNameResources.Name.JENNIFER -> R.string.ghost_name_jennifer
        GhostNameResources.Name.JENNISE -> R.string.ghost_name_jennise
        GhostNameResources.Name.JERRY -> R.string.ghost_name_jerry
        GhostNameResources.Name.JESSICA -> R.string.ghost_name_jessica
        GhostNameResources.Name.JO -> R.string.ghost_name_jo
        GhostNameResources.Name.JOHN -> R.string.ghost_name_john
        GhostNameResources.Name.JOSEFINE -> R.string.ghost_name_josefine
        GhostNameResources.Name.JOSEPH -> R.string.ghost_name_joseph
        GhostNameResources.Name.JUDY -> R.string.ghost_name_judy
        GhostNameResources.Name.JULIE -> R.string.ghost_name_julie
        GhostNameResources.Name.JUSTIN -> R.string.ghost_name_justin
        GhostNameResources.Name.KAREN -> R.string.ghost_name_karen
        GhostNameResources.Name.KATE -> R.string.ghost_name_kate
        GhostNameResources.Name.KEITH -> R.string.ghost_name_keith
        GhostNameResources.Name.KELLY -> R.string.ghost_name_kelly
        GhostNameResources.Name.KENNETH -> R.string.ghost_name_kenneth
        GhostNameResources.Name.KENNY -> R.string.ghost_name_kenny
        GhostNameResources.Name.KEVIN -> R.string.ghost_name_kevin
        GhostNameResources.Name.KIM -> R.string.ghost_name_kim
        GhostNameResources.Name.KYLE -> R.string.ghost_name_kyle
        GhostNameResources.Name.LARRY -> R.string.ghost_name_larry
        GhostNameResources.Name.LESLIE -> R.string.ghost_name_leslie
        GhostNameResources.Name.LINDA -> R.string.ghost_name_linda
        GhostNameResources.Name.LISA -> R.string.ghost_name_lisa
        GhostNameResources.Name.LIVY -> R.string.ghost_name_livy
        GhostNameResources.Name.LORI -> R.string.ghost_name_lori
        GhostNameResources.Name.LUCY -> R.string.ghost_name_lucy
        GhostNameResources.Name.LUKE -> R.string.ghost_name_luke
        GhostNameResources.Name.MARCIA -> R.string.ghost_name_marcia
        GhostNameResources.Name.MARGARET -> R.string.ghost_name_margaret
        GhostNameResources.Name.MARIA -> R.string.ghost_name_maria
        GhostNameResources.Name.MARIE -> R.string.ghost_name_marie
        GhostNameResources.Name.MARK -> R.string.ghost_name_mark
        GhostNameResources.Name.MARY -> R.string.ghost_name_mary
        GhostNameResources.Name.MEGAN -> R.string.ghost_name_megan
        GhostNameResources.Name.MICHAEL -> R.string.ghost_name_michael
        GhostNameResources.Name.MICHELLE -> R.string.ghost_name_michelle
        GhostNameResources.Name.NANCY -> R.string.ghost_name_nancy
        GhostNameResources.Name.NELLIE -> R.string.ghost_name_nellie
        GhostNameResources.Name.PATRICIA -> R.string.ghost_name_patricia
        GhostNameResources.Name.PAUL -> R.string.ghost_name_paul
        GhostNameResources.Name.PETER -> R.string.ghost_name_peter
        GhostNameResources.Name.RAYMOND -> R.string.ghost_name_raymond
        GhostNameResources.Name.RICHARD -> R.string.ghost_name_richard
        GhostNameResources.Name.ROBERT -> R.string.ghost_name_robert
        GhostNameResources.Name.ROBIN -> R.string.ghost_name_robin
        GhostNameResources.Name.RONALD -> R.string.ghost_name_ronald
        GhostNameResources.Name.ROSE -> R.string.ghost_name_rose
        GhostNameResources.Name.RUSSELL -> R.string.ghost_name_russell
        GhostNameResources.Name.RUTH -> R.string.ghost_name_ruth
        GhostNameResources.Name.SANDRA -> R.string.ghost_name_sandra
        GhostNameResources.Name.SARAH -> R.string.ghost_name_sarah
        GhostNameResources.Name.SHANNON -> R.string.ghost_name_shannon
        GhostNameResources.Name.SHARNE -> R.string.ghost_name_sharne
        GhostNameResources.Name.SHELLY -> R.string.ghost_name_shelly
        GhostNameResources.Name.SOPHIE -> R.string.ghost_name_sophie
        GhostNameResources.Name.STACEY -> R.string.ghost_name_stacey
        GhostNameResources.Name.STEVEN -> R.string.ghost_name_steven
        GhostNameResources.Name.SUSAN -> R.string.ghost_name_susan
        GhostNameResources.Name.TED -> R.string.ghost_name_ted
        GhostNameResources.Name.THOMAS -> R.string.ghost_name_thomas
        GhostNameResources.Name.TIM -> R.string.ghost_name_tim
        GhostNameResources.Name.TRICIA -> R.string.ghost_name_tricia
        GhostNameResources.Name.WALTER -> R.string.ghost_name_walter
        GhostNameResources.Name.WILLIAM -> R.string.ghost_name_william
        GhostNameResources.Name.ALEXANDER -> R.string.ghost_name_alexander
        GhostNameResources.Name.ANDERSON -> R.string.ghost_name_anderson
        GhostNameResources.Name.BAILEY -> R.string.ghost_name_bailey
        GhostNameResources.Name.BAKER -> R.string.ghost_name_baker
        GhostNameResources.Name.BARBER -> R.string.ghost_name_barber
        GhostNameResources.Name.BARTON -> R.string.ghost_name_barton
        GhostNameResources.Name.BELLFIELD -> R.string.ghost_name_bellfield
        GhostNameResources.Name.BIRCH -> R.string.ghost_name_birch
        GhostNameResources.Name.BISHOP -> R.string.ghost_name_bishop
        GhostNameResources.Name.BOWEN -> R.string.ghost_name_bowen
        GhostNameResources.Name.BROCK -> R.string.ghost_name_brock
        GhostNameResources.Name.BROOKS -> R.string.ghost_name_brooks
        GhostNameResources.Name.BROWN -> R.string.ghost_name_brown
        GhostNameResources.Name.BUCKLEY -> R.string.ghost_name_buckley
        GhostNameResources.Name.CAREY -> R.string.ghost_name_carey
        GhostNameResources.Name.CARTER -> R.string.ghost_name_carter
        GhostNameResources.Name.CLARK -> R.string.ghost_name_clark
        GhostNameResources.Name.CLARKE -> R.string.ghost_name_clarke
        GhostNameResources.Name.CORDERO -> R.string.ghost_name_cordero
        GhostNameResources.Name.CORRIGAN -> R.string.ghost_name_corrigan
        GhostNameResources.Name.DAVIS -> R.string.ghost_name_davis
        GhostNameResources.Name.DEXTER -> R.string.ghost_name_dexter
        GhostNameResources.Name.DIXON -> R.string.ghost_name_dixon
        GhostNameResources.Name.DOE -> R.string.ghost_name_doe
        GhostNameResources.Name.DOUGLAS -> R.string.ghost_name_douglas
        GhostNameResources.Name.DYER -> R.string.ghost_name_dyer
        GhostNameResources.Name.ELLIOTT -> R.string.ghost_name_elliott
        GhostNameResources.Name.EMMETT -> R.string.ghost_name_emmett
        GhostNameResources.Name.EVERLY -> R.string.ghost_name_everly
        GhostNameResources.Name.GACY -> R.string.ghost_name_gacy
        GhostNameResources.Name.GARCIA -> R.string.ghost_name_garcia
        GhostNameResources.Name.GAYTON -> R.string.ghost_name_gayton
        GhostNameResources.Name.HALSTEAD -> R.string.ghost_name_halstead
        GhostNameResources.Name.HANS -> R.string.ghost_name_hans
        GhostNameResources.Name.HARRIS -> R.string.ghost_name_harris
        GhostNameResources.Name.HILL -> R.string.ghost_name_hill
        GhostNameResources.Name.HOLLAND -> R.string.ghost_name_holland
        GhostNameResources.Name.HOLMES -> R.string.ghost_name_holmes
        GhostNameResources.Name.HUNTLEY -> R.string.ghost_name_huntley
        GhostNameResources.Name.JACKSON -> R.string.ghost_name_jackson
        GhostNameResources.Name.JOHNSON -> R.string.ghost_name_johnson
        GhostNameResources.Name.JONES -> R.string.ghost_name_jones
        GhostNameResources.Name.KEMPER -> R.string.ghost_name_kemper
        GhostNameResources.Name.KNIGHT -> R.string.ghost_name_knight
        GhostNameResources.Name.KRAFT -> R.string.ghost_name_kraft
        GhostNameResources.Name.KRAY -> R.string.ghost_name_kray
        GhostNameResources.Name.LANCASTER -> R.string.ghost_name_lancaster
        GhostNameResources.Name.LAVENDER -> R.string.ghost_name_lavender
        GhostNameResources.Name.LEE -> R.string.ghost_name_lee
        GhostNameResources.Name.LEWIS -> R.string.ghost_name_lewis
        GhostNameResources.Name.MANSON -> R.string.ghost_name_manson
        GhostNameResources.Name.MARSH -> R.string.ghost_name_marsh
        GhostNameResources.Name.MARTIN -> R.string.ghost_name_martin
        GhostNameResources.Name.MARTINEZ -> R.string.ghost_name_martinez
        GhostNameResources.Name.MAUDSLEY -> R.string.ghost_name_maudsley
        GhostNameResources.Name.MILLER -> R.string.ghost_name_miller
        GhostNameResources.Name.MILLS -> R.string.ghost_name_mills
        GhostNameResources.Name.MOORE -> R.string.ghost_name_moore
        GhostNameResources.Name.MYERS -> R.string.ghost_name_myers
        GhostNameResources.Name.NILSEN -> R.string.ghost_name_nilsen
        GhostNameResources.Name.NORRIS -> R.string.ghost_name_norris
        GhostNameResources.Name.PETTIT -> R.string.ghost_name_pettit
        GhostNameResources.Name.PHILLIPS -> R.string.ghost_name_phillips
        GhostNameResources.Name.RAMIREZ -> R.string.ghost_name_ramirez
        GhostNameResources.Name.RHOADES -> R.string.ghost_name_rhoades
        GhostNameResources.Name.ROBERTS -> R.string.ghost_name_roberts
        GhostNameResources.Name.ROBINSON -> R.string.ghost_name_robinson
        GhostNameResources.Name.ROOK -> R.string.ghost_name_rook
        GhostNameResources.Name.ROSWELL -> R.string.ghost_name_roswell
        GhostNameResources.Name.SCHELIN -> R.string.ghost_name_schelin
        GhostNameResources.Name.SHAWCROSS -> R.string.ghost_name_shawcross
        GhostNameResources.Name.SHERMAN -> R.string.ghost_name_sherman
        GhostNameResources.Name.SHIPMAN -> R.string.ghost_name_shipman
        GhostNameResources.Name.SKINNER -> R.string.ghost_name_skinner
        GhostNameResources.Name.SMITH -> R.string.ghost_name_smith
        GhostNameResources.Name.STEVENS -> R.string.ghost_name_stevens
        GhostNameResources.Name.STRAFFEN -> R.string.ghost_name_straffen
        GhostNameResources.Name.SWEENEY -> R.string.ghost_name_sweeney
        GhostNameResources.Name.TAYLOR -> R.string.ghost_name_taylor
        GhostNameResources.Name.THOMPSON -> R.string.ghost_name_thompson
        GhostNameResources.Name.TODD -> R.string.ghost_name_todd
        GhostNameResources.Name.WALKER -> R.string.ghost_name_walker
        GhostNameResources.Name.WATTS -> R.string.ghost_name_watts
        GhostNameResources.Name.WEST -> R.string.ghost_name_west
        GhostNameResources.Name.WHITE -> R.string.ghost_name_white
        GhostNameResources.Name.WILLIAMS -> R.string.ghost_name_williams
        GhostNameResources.Name.WILSON -> R.string.ghost_name_wilson
        GhostNameResources.Name.WINTER -> R.string.ghost_name_winter
        GhostNameResources.Name.WRIGHT -> R.string.ghost_name_wright
        GhostNameResources.Name.YOUNG -> R.string.ghost_name_young
    }