package com.tritiumgaming.phasmophobiaevidencepicker.operation.domain.popup.source

import com.tritiumgaming.phasmophobiaevidencepicker.operation.domain.popup.model.EvidencePopupRecord

interface EvidencePopupDataSource: PopupDataSource<EvidencePopupRecord>