package com.tritiumstudios.feature.investigation.app.mappers.codex

import androidx.annotation.DrawableRes
import androidx.annotation.IntegerRes
import androidx.annotation.StringRes
import com.tritiumgaming.core.resources.R
import com.tritiumgaming.shared.operation.domain.codex.mappers.EquipmentResources.BuyCost
import com.tritiumgaming.shared.operation.domain.codex.mappers.EquipmentResources.EquipmentAttribute
import com.tritiumgaming.shared.operation.domain.codex.mappers.EquipmentResources.EquipmentBuyCost
import com.tritiumgaming.shared.operation.domain.codex.mappers.EquipmentResources.EquipmentIcon
import com.tritiumgaming.shared.operation.domain.codex.mappers.EquipmentResources.EquipmentTierFlavorText
import com.tritiumgaming.shared.operation.domain.codex.mappers.EquipmentResources.EquipmentTierImage
import com.tritiumgaming.shared.operation.domain.codex.mappers.EquipmentResources.EquipmentTierInformation
import com.tritiumgaming.shared.operation.domain.codex.mappers.EquipmentResources.EquipmentTitle
import com.tritiumgaming.shared.operation.domain.codex.mappers.EquipmentResources.EquipmentUnlockLevel
import com.tritiumgaming.shared.operation.domain.codex.mappers.EquipmentResources.EquipmentUpgradeCost

@StringRes fun EquipmentTitle.toStringResource(): Int =
    when (this) {
        EquipmentTitle.DOTS -> R.string.equipment_info_name_dots
        EquipmentTitle.EMF -> R.string.equipment_info_name_emf
        EquipmentTitle.FLASHLIGHT -> R.string.equipment_info_name_flashlight
        EquipmentTitle.PHOTO_CAMERA -> R.string.equipment_info_name_photocamera
        EquipmentTitle.IGNITER -> R.string.equipment_info_name_igniter
        EquipmentTitle.FIRELIGHT -> R.string.equipment_info_name_firelight
        EquipmentTitle.UV_LIGHT -> R.string.equipment_info_name_uvlight
        EquipmentTitle.CRUCIFIX -> R.string.equipment_info_name_crucifix
        EquipmentTitle.VIDEO_CAMERA -> R.string.equipment_info_name_videocamera
        EquipmentTitle.SPIRIT_BOX -> R.string.equipment_info_name_spiritbox
        EquipmentTitle.THERMOMETER -> R.string.equipment_info_name_thermometer
        EquipmentTitle.SALT -> R.string.equipment_info_name_salt
        EquipmentTitle.INCENSE -> R.string.equipment_info_name_incense
        EquipmentTitle.TRIPOD -> R.string.equipment_info_name_tripod
        EquipmentTitle.MOTION_SENSOR -> R.string.equipment_info_name_motionsensor
        EquipmentTitle.SOUND_RECORDER -> R.string.equipment_info_name_soundrecorder
        EquipmentTitle.SOUND_SENSOR -> R.string.equipment_info_name_soundsensor
        EquipmentTitle.SANITY_MEDICATION -> R.string.equipment_info_name_sanitymedication
        EquipmentTitle.GHOST_WRITING_BOOK -> R.string.equipment_info_name_ghostwritingbook
        EquipmentTitle.PARABOLIC_MICROPHONE -> R.string.equipment_info_name_parabolicmicrophone
        EquipmentTitle.HEAD_GEAR -> R.string.equipment_info_name_headgear
    }

@DrawableRes fun EquipmentIcon.toDrawableResource(): Int =
    when (this) {
        EquipmentIcon.DOTS -> R.drawable.icon_sh_dotsprojector
        EquipmentIcon.EMF -> R.drawable.icon_sh_emf
        EquipmentIcon.FLASHLIGHT -> R.drawable.icon_sh_flashlight
        EquipmentIcon.PHOTO_CAMERA -> R.drawable.icon_sh_photocamera
        EquipmentIcon.IGNITER -> R.drawable.icon_sh_igniter
        EquipmentIcon.FIRELIGHT -> R.drawable.icon_sh_firelight
        EquipmentIcon.UV_LIGHT -> R.drawable.icon_sh_uvlight
        EquipmentIcon.CRUCIFIX -> R.drawable.icon_sh_crucifix
        EquipmentIcon.VIDEO_CAMERA -> R.drawable.icon_sh_videocamera
        EquipmentIcon.SPIRIT_BOX -> R.drawable.icon_sh_spiritbox
        EquipmentIcon.THERMOMETER -> R.drawable.icon_sh_thermometer
        EquipmentIcon.SALT -> R.drawable.icon_sh_salt
        EquipmentIcon.INCENSE -> R.drawable.icon_sh_smudge
        EquipmentIcon.TRIPOD -> R.drawable.icon_sh_tripod
        EquipmentIcon.MOTION_SENSOR -> R.drawable.icon_sh_motionsensor
        EquipmentIcon.SOUND_RECORDER -> R.drawable.icon_sh_soundrecorder
        EquipmentIcon.SOUND_SENSOR -> R.drawable.icon_sh_soundsensor
        EquipmentIcon.SANITY_MEDICATION -> R.drawable.icon_sh_sanitymedication
        EquipmentIcon.GHOST_WRITING_BOOK -> R.drawable.icon_sh_ghostwritingbook
        EquipmentIcon.PARABOLIC_MICROPHONE -> R.drawable.icon_sh_parabolicmicrophone
        EquipmentIcon.HEAD_GEAR -> R.drawable.icon_sh_headgear
    }

@StringRes fun EquipmentAttribute.toStringResource(): Int =
    when (this) {
        EquipmentAttribute.SPOTLIGHT_NARROW -> R.string.shop_equipment_attribute_spotight_narrow
        EquipmentAttribute.SPOTLIGHT_WIDE -> R.string.shop_equipment_attribute_spotight_wide
        EquipmentAttribute.SPOTLIGHT_AREA -> R.string.shop_equipment_attribute_spotight_area
        EquipmentAttribute.INTENSITY_LOW -> R.string.shop_equipment_attribute_intensity_low
        EquipmentAttribute.INTENSITY_MED -> R.string.shop_equipment_attribute_intensity_med
        EquipmentAttribute.INTENSITY_HIGH -> R.string.shop_equipment_attribute_intensity_high
        EquipmentAttribute.INTERACTION_RATE_LOW -> R.string.shop_equipment_attribute_interactionrate_low
        EquipmentAttribute.INTERACTION_RATE_MED -> R.string.shop_equipment_attribute_interactionrate_med
        EquipmentAttribute.INTERACTION_RATE_HIGH -> R.string.shop_equipment_attribute_interactionrate_high
        EquipmentAttribute.AUDIO_QUALITY_LOW -> R.string.shop_equipment_attribute_audioquality_low
        EquipmentAttribute.AUDIO_QUALITY_MED -> R.string.shop_equipment_attribute_audioquality_med
        EquipmentAttribute.AUDIO_QUALITY_HIGH -> R.string.shop_equipment_attribute_audioquality_high
        EquipmentAttribute.RESPONSE_RATE_LOW -> R.string.shop_equipment_attribute_responserate_low
        EquipmentAttribute.RESPONSE_RATE_MED -> R.string.shop_equipment_attribute_responserate_med
        EquipmentAttribute.RESPONSE_RATE_HIGH -> R.string.shop_equipment_attribute_responserate_high
        EquipmentAttribute.SAMPLE_SPEED_LOW -> R.string.shop_equipment_attribute_samplespeed_low
        EquipmentAttribute.SAMPLE_SPEED_MED -> R.string.shop_equipment_attribute_samplespeed_med
        EquipmentAttribute.SAMPLE_SPEED_HIGH -> R.string.shop_equipment_attribute_samplespeed_high
        EquipmentAttribute.IMAGE_QUALITY_LOW -> R.string.shop_equipment_attribute_imagequality_low
        EquipmentAttribute.IMAGE_QUALITY_MED -> R.string.shop_equipment_attribute_imagequality_med
        EquipmentAttribute.IMAGE_QUALITY_HIGH -> R.string.shop_equipment_attribute_imagequality_high
        EquipmentAttribute.INTERFERENCE_LOW -> R.string.shop_equipment_attribute_interference_low
        EquipmentAttribute.INTERFERENCE_MED -> R.string.shop_equipment_attribute_interference_med
        EquipmentAttribute.INTERFERENCE_HIGH -> R.string.shop_equipment_attribute_interference_high
        EquipmentAttribute.KNOCKDOWN_CHANCE_LOW -> R.string.shop_equipment_attribute_knockdownchance_low
        EquipmentAttribute.KNOCKDOWN_CHANCE_MED -> R.string.shop_equipment_attribute_knockdownchance_med
        EquipmentAttribute.KNOCKDOWN_CHANCE_HIGH -> R.string.shop_equipment_attribute_knockdownchance_high
        EquipmentAttribute.ACCURACY_LOW -> R.string.shop_equipment_attribute_accuracy_low
        EquipmentAttribute.ACCURACY_MED -> R.string.shop_equipment_attribute_accuracy_med
        EquipmentAttribute.ACCURACY_HIGH -> R.string.shop_equipment_attribute_accuracy_high
        EquipmentAttribute.INDICATOR_AUDIO -> R.string.shop_equipment_attribute_indicator_audio
        EquipmentAttribute.INDICATOR_LIGHT -> R.string.shop_equipment_attribute_indicator_light
        EquipmentAttribute.INDICATOR_DISTANCE -> R.string.shop_equipment_attribute_indicator_distance
        EquipmentAttribute.INDICATOR_DIRECTIONAL -> R.string.shop_equipment_attribute_indicator_directional
        EquipmentAttribute.RANGE_1_7 -> R.string.shop_equipment_attribute_range_1_7
        EquipmentAttribute.RANGE_2 -> R.string.shop_equipment_attribute_range_2
        EquipmentAttribute.RANGE_2_5 -> R.string.shop_equipment_attribute_range_2_5
        EquipmentAttribute.RANGE_3 -> R.string.shop_equipment_attribute_range_3
        EquipmentAttribute.RANGE_3_5 -> R.string.shop_equipment_attribute_range_3_5
        EquipmentAttribute.RANGE_4 -> R.string.shop_equipment_attribute_range_4
        EquipmentAttribute.RANGE_5 -> R.string.shop_equipment_attribute_range_5
        EquipmentAttribute.RANGE_7 -> R.string.shop_equipment_attribute_range_7
        EquipmentAttribute.RANGE_20 -> R.string.shop_equipment_attribute_range_20
        EquipmentAttribute.RANGE_30 -> R.string.shop_equipment_attribute_range_30
        EquipmentAttribute.RANGE_5_10 -> R.string.shop_equipment_attribute_range_5_10
        EquipmentAttribute.RANGE_5_10_15 -> R.string.shop_equipment_attribute_range_5_10_15
        EquipmentAttribute.UV_CHARGE_TIME_1_5 -> R.string.shop_equipment_attribute_uvchargetime_1_5
        EquipmentAttribute.UV_CHARGE_TIME_5 -> R.string.shop_equipment_attribute_uvchargetime_5
        EquipmentAttribute.UV_CHARGE_TIME_10 -> R.string.shop_equipment_attribute_uvchargetime_10
        EquipmentAttribute.PHOTO_TIME_LOW -> R.string.shop_equipment_attribute_phototime_low
        EquipmentAttribute.PHOTO_TIME_MED -> R.string.shop_equipment_attribute_phototime_med
        EquipmentAttribute.PHOTO_TIME_HIGH -> R.string.shop_equipment_attribute_phototime_high
        EquipmentAttribute.SANITY_DRAIN_REDUCTION_33 -> R.string.shop_equipment_attribute_sanitydrainreduction_33
        EquipmentAttribute.SANITY_DRAIN_REDUCTION_50 -> R.string.shop_equipment_attribute_sanitydrainreduction_50
        EquipmentAttribute.SANITY_DRAIN_REDUCTION_66 -> R.string.shop_equipment_attribute_sanitydrainreduction_66
        EquipmentAttribute.SANITY_RESTORATION_10 -> R.string.shop_equipment_attribute_sanityrestoration_10
        EquipmentAttribute.SANITY_RESTORATION_20 -> R.string.shop_equipment_attribute_sanityrestoration_20
        EquipmentAttribute.SANITY_RESTORATION_30 -> R.string.shop_equipment_attribute_sanityrestoration_30
        EquipmentAttribute.SENSOR_SHAPE_LINE -> R.string.shop_equipment_attribute_sensorshape_line
        EquipmentAttribute.SENSOR_SHAPE_LINE_CONE -> R.string.shop_equipment_attribute_sensorshape_line_cone
        EquipmentAttribute.SENSOR_SHAPE_CIRCLE -> R.string.shop_equipment_attribute_sensorshape_circle
        EquipmentAttribute.SENSOR_SHAPE_CIRCLE_CONE_SIDES -> R.string.shop_equipment_attribute_sensorshape_circle_cone_sides
        EquipmentAttribute.DURATION_3_S -> R.string.shop_equipment_attribute_duration_3_s
        EquipmentAttribute.DURATION_5_S -> R.string.shop_equipment_attribute_duration_5_s
        EquipmentAttribute.DURATION_6_S -> R.string.shop_equipment_attribute_duration_6_s
        EquipmentAttribute.DURATION_7_S -> R.string.shop_equipment_attribute_duration_7_s
        EquipmentAttribute.DURATION_10_S -> R.string.shop_equipment_attribute_duration_10_s
        EquipmentAttribute.DURATION_60_S -> R.string.shop_equipment_attribute_duration_60_s
        EquipmentAttribute.DURATION_3_M -> R.string.shop_equipment_attribute_duration_3_m
        EquipmentAttribute.DURATION_5_M -> R.string.shop_equipment_attribute_duration_5_m
        EquipmentAttribute.DURATION_10_M -> R.string.shop_equipment_attribute_duration_10_m
        EquipmentAttribute.USES_1 -> R.string.shop_equipment_attribute_uses_1
        EquipmentAttribute.USES_2 -> R.string.shop_equipment_attribute_uses_2
        EquipmentAttribute.USES_3 -> R.string.shop_equipment_attribute_uses_3
        EquipmentAttribute.USES_10 -> R.string.shop_equipment_attribute_uses_10
        EquipmentAttribute.PLACEABLE -> R.string.shop_equipment_attribute_placeable
        EquipmentAttribute.HANDHELD -> R.string.shop_equipment_attribute_handheld
        EquipmentAttribute.PROPERTY_GHOST_EFFECT_SLOWS -> R.string.shop_equipment_attribute_property_ghosteffect_slows
        EquipmentAttribute.PROPERTY_GHOST_EFFECT_HALTS -> R.string.shop_equipment_attribute_property_ghosteffect_halts
        EquipmentAttribute.PROPERTY_DISPLAY_SCREEN -> R.string.shop_equipment_attribute_property_displayscreen
        EquipmentAttribute.PROPERTY_PREVENT_CURSED_HUNT -> R.string.shop_equipment_attribute_property_preventscursedhunt
        EquipmentAttribute.PROPERTY_ELECTRONIC -> R.string.shop_equipment_attribute_property_electronic
        EquipmentAttribute.PROPERTY_CONSUMABLE -> R.string.shop_equipment_attribute_property_consumable
        EquipmentAttribute.PROPERTY_WATERPROOF -> R.string.shop_equipment_attribute_property_waterproof
        EquipmentAttribute.PROPERTY_HEAD_SLOT -> R.string.shop_equipment_attribute_property_headslot
        EquipmentAttribute.PROPERTY_NIGHT_VISION -> R.string.shop_equipment_attribute_property_nightvision
        EquipmentAttribute.PROPERTY_SPRINT_BOOST -> R.string.shop_equipment_attribute_property_sprintboost
        EquipmentAttribute.PROPERTY_ROTATION_CONTROL -> R.string.shop_equipment_attribute_property_rotationcontrol
        EquipmentAttribute.PROPERTY_SCANNING -> R.string.shop_equipment_attribute_property_scanning
    }

@DrawableRes fun EquipmentTierImage.toDrawableResource(): Int =
    when (this) {
        EquipmentTierImage.DOTS_1 -> R.drawable.icon_shop_dots_1
        EquipmentTierImage.DOTS_2 -> R.drawable.icon_shop_dots_2
        EquipmentTierImage.DOTS_3 -> R.drawable.icon_shop_dots_3
        EquipmentTierImage.EMF_1 -> R.drawable.icon_shop_emf_1
        EquipmentTierImage.EMF_2 -> R.drawable.icon_shop_emf_2
        EquipmentTierImage.EMF_3 -> R.drawable.icon_shop_emf_3
        EquipmentTierImage.FLASHLIGHT_1 -> R.drawable.icon_shop_flashlight_1
        EquipmentTierImage.FLASHLIGHT_2 -> R.drawable.icon_shop_flashlight_2
        EquipmentTierImage.FLASHLIGHT_3 -> R.drawable.icon_shop_flashlight_3
        EquipmentTierImage.PHOTO_CAMERA_1 -> R.drawable.icon_shop_photocam_1
        EquipmentTierImage.PHOTO_CAMERA_2 -> R.drawable.icon_shop_photocam_2
        EquipmentTierImage.PHOTO_CAMERA_3 -> R.drawable.icon_shop_photocam_3
        EquipmentTierImage.IGNITER_1 -> R.drawable.icon_shop_igniter_1
        EquipmentTierImage.IGNITER_2 -> R.drawable.icon_shop_igniter_2
        EquipmentTierImage.IGNITER_3 -> R.drawable.icon_shop_igniter_3
        EquipmentTierImage.FIRELIGHT_1 -> R.drawable.icon_shop_firelight_1
        EquipmentTierImage.FIRELIGHT_2 -> R.drawable.icon_shop_firelight_2
        EquipmentTierImage.FIRELIGHT_3 -> R.drawable.icon_shop_firelight_3
        EquipmentTierImage.UV_LIGHT_1 -> R.drawable.icon_shop_uv_1
        EquipmentTierImage.UV_LIGHT_2 -> R.drawable.icon_shop_uv_2
        EquipmentTierImage.UV_LIGHT_3 -> R.drawable.icon_shop_uv_3
        EquipmentTierImage.CRUCIFIX_1 -> R.drawable.icon_shop_crucifix_1
        EquipmentTierImage.CRUCIFIX_2 -> R.drawable.icon_shop_crucifix_2
        EquipmentTierImage.CRUCIFIX_3 -> R.drawable.icon_shop_crucifix_3
        EquipmentTierImage.VIDEO_CAMERA_1 -> R.drawable.icon_shop_vidcam_1
        EquipmentTierImage.VIDEO_CAMERA_2 -> R.drawable.icon_shop_vidcam_2
        EquipmentTierImage.VIDEO_CAMERA_3 -> R.drawable.icon_shop_vidcam_3
        EquipmentTierImage.SPIRIT_BOX_1 -> R.drawable.icon_shop_spiritbox_1
        EquipmentTierImage.SPIRIT_BOX_2 -> R.drawable.icon_shop_spiritbox_2
        EquipmentTierImage.SPIRIT_BOX_3 -> R.drawable.icon_shop_spiritbox_3
        EquipmentTierImage.THERMOMETER_1 -> R.drawable.icon_shop_thermo_1
        EquipmentTierImage.THERMOMETER_2 -> R.drawable.icon_shop_thermo_2
        EquipmentTierImage.THERMOMETER_3 -> R.drawable.icon_shop_thermo_3
        EquipmentTierImage.SALT_1 -> R.drawable.icon_shop_salt_1
        EquipmentTierImage.SALT_2 -> R.drawable.icon_shop_salt_2
        EquipmentTierImage.SALT_3 -> R.drawable.icon_shop_salt_3
        EquipmentTierImage.INCENSE_1 -> R.drawable.icon_shop_repellant_1
        EquipmentTierImage.INCENSE_2 -> R.drawable.icon_shop_repellant_2
        EquipmentTierImage.INCENSE_3 -> R.drawable.icon_shop_repellant_3
        EquipmentTierImage.TRIPOD_1 -> R.drawable.icon_shop_tripod_1
        EquipmentTierImage.TRIPOD_2 -> R.drawable.icon_shop_tripod_2
        EquipmentTierImage.TRIPOD_3 -> R.drawable.icon_shop_tripod_3
        EquipmentTierImage.MOTION_SENSOR_1 -> R.drawable.icon_shop_motion_1
        EquipmentTierImage.MOTION_SENSOR_2 -> R.drawable.icon_shop_motion_2
        EquipmentTierImage.MOTION_SENSOR_3 -> R.drawable.icon_shop_motion_3
        EquipmentTierImage.SOUND_RECORDER_1 -> R.drawable.icon_shop_soundrecorder_1
        EquipmentTierImage.SOUND_RECORDER_2 -> R.drawable.icon_shop_soundrecorder_2
        EquipmentTierImage.SOUND_RECORDER_3 -> R.drawable.icon_shop_soundrecorder_3
        EquipmentTierImage.SOUND_SENSOR_1 -> R.drawable.icon_shop_soundsensor_1
        EquipmentTierImage.SOUND_SENSOR_2 -> R.drawable.icon_shop_soundsensor_2
        EquipmentTierImage.SOUND_SENSOR_3 -> R.drawable.icon_shop_soundsensor_3
        EquipmentTierImage.SANITY_MEDICATION_1 -> R.drawable.icon_shop_sanity_1
        EquipmentTierImage.SANITY_MEDICATION_2 -> R.drawable.icon_shop_sanity_2
        EquipmentTierImage.SANITY_MEDICATION_3 -> R.drawable.icon_shop_sanity_3
        EquipmentTierImage.GHOST_WRITING_BOOK_1 -> R.drawable.icon_shop_writing_1
        EquipmentTierImage.GHOST_WRITING_BOOK_2 -> R.drawable.icon_shop_writing_2
        EquipmentTierImage.GHOST_WRITING_BOOK_3 -> R.drawable.icon_shop_writing_3
        EquipmentTierImage.PARABOLIC_MICROPHONE_1 -> R.drawable.icon_shop_para_1
        EquipmentTierImage.PARABOLIC_MICROPHONE_2 -> R.drawable.icon_shop_para_2
        EquipmentTierImage.PARABOLIC_MICROPHONE_3 -> R.drawable.icon_shop_para_3
        EquipmentTierImage.HEAD_GEAR_1 -> R.drawable.icon_shop_headgear_1
        EquipmentTierImage.HEAD_GEAR_2 -> R.drawable.icon_shop_headgear_2
        EquipmentTierImage.HEAD_GEAR_3 -> R.drawable.icon_shop_headgear_3
    }

@StringRes fun EquipmentTierInformation.toStringResource(): Int =
    when (this) {
        EquipmentTierInformation.DOTS_1 -> R.string.shop_equipment_dots_data_info_1
        EquipmentTierInformation.DOTS_2 -> R.string.shop_equipment_dots_data_info_2
        EquipmentTierInformation.DOTS_3 -> R.string.shop_equipment_dots_data_info_3
        EquipmentTierInformation.EMF_1 -> R.string.shop_equipment_emf_data_info_1
        EquipmentTierInformation.EMF_2 -> R.string.shop_equipment_emf_data_info_2
        EquipmentTierInformation.EMF_3 -> R.string.shop_equipment_emf_data_info_3
        EquipmentTierInformation.FLASHLIGHT_1 -> R.string.shop_equipment_flashlight_data_info_1
        EquipmentTierInformation.FLASHLIGHT_2 -> R.string.shop_equipment_flashlight_data_info_2
        EquipmentTierInformation.FLASHLIGHT_3 -> R.string.shop_equipment_flashlight_data_info_3
        EquipmentTierInformation.PHOTO_CAMERA_1 -> R.string.shop_equipment_photocamera_data_info_1
        EquipmentTierInformation.PHOTO_CAMERA_2 -> R.string.shop_equipment_photocamera_data_info_2
        EquipmentTierInformation.PHOTO_CAMERA_3 -> R.string.shop_equipment_photocamera_data_info_3
        EquipmentTierInformation.IGNITER_1 -> R.string.shop_equipment_igniter_data_info_1
        EquipmentTierInformation.IGNITER_2 -> R.string.shop_equipment_igniter_data_info_2
        EquipmentTierInformation.IGNITER_3 -> R.string.shop_equipment_igniter_data_info_3
        EquipmentTierInformation.FIRELIGHT_1 -> R.string.shop_equipment_firelight_data_info_1
        EquipmentTierInformation.FIRELIGHT_2 -> R.string.shop_equipment_firelight_data_info_2
        EquipmentTierInformation.FIRELIGHT_3 -> R.string.shop_equipment_firelight_data_info_3
        EquipmentTierInformation.UV_LIGHT_1 -> R.string.shop_equipment_uvlight_data_info_2
        EquipmentTierInformation.UV_LIGHT_2 -> R.string.shop_equipment_uvlight_data_info_1
        EquipmentTierInformation.UV_LIGHT_3 -> R.string.shop_equipment_uvlight_data_info_3
        EquipmentTierInformation.CRUCIFIX_1 -> R.string.shop_equipment_crucifix_data_info_1
        EquipmentTierInformation.CRUCIFIX_2 -> R.string.shop_equipment_crucifix_data_info_2
        EquipmentTierInformation.CRUCIFIX_3 -> R.string.shop_equipment_crucifix_data_info_3
        EquipmentTierInformation.VIDEO_CAMERA_1 -> R.string.shop_equipment_videocamera_data_info_1
        EquipmentTierInformation.VIDEO_CAMERA_2 -> R.string.shop_equipment_videocamera_data_info_2
        EquipmentTierInformation.VIDEO_CAMERA_3 -> R.string.shop_equipment_videocamera_data_info_3
        EquipmentTierInformation.SPIRIT_BOX_1 -> R.string.shop_equipment_spiritbox_data_info_1
        EquipmentTierInformation.SPIRIT_BOX_2 -> R.string.shop_equipment_spiritbox_data_info_2
        EquipmentTierInformation.SPIRIT_BOX_3 -> R.string.shop_equipment_spiritbox_data_info_3
        EquipmentTierInformation.THERMOMETER_1 -> R.string.shop_equipment_thermometer_data_info_1
        EquipmentTierInformation.THERMOMETER_2 -> R.string.shop_equipment_thermometer_data_info_2
        EquipmentTierInformation.THERMOMETER_3 -> R.string.shop_equipment_thermometer_data_info_3
        EquipmentTierInformation.SALT_1 -> R.string.shop_equipment_salt_data_info_1
        EquipmentTierInformation.SALT_2 -> R.string.shop_equipment_salt_data_info_2
        EquipmentTierInformation.SALT_3 -> R.string.shop_equipment_salt_data_info_3
        EquipmentTierInformation.INCENSE_1 -> R.string.shop_equipment_incense_data_info_1
        EquipmentTierInformation.INCENSE_2 -> R.string.shop_equipment_incense_data_info_2
        EquipmentTierInformation.INCENSE_3 -> R.string.shop_equipment_incense_data_info_3
        EquipmentTierInformation.TRIPOD_1 -> R.string.shop_equipment_tripod_data_info_1
        EquipmentTierInformation.TRIPOD_2 -> R.string.shop_equipment_tripod_data_info_2
        EquipmentTierInformation.TRIPOD_3 -> R.string.shop_equipment_tripod_data_info_3
        EquipmentTierInformation.MOTION_SENSOR_1 -> R.string.shop_equipment_motionsensor_data_info_1
        EquipmentTierInformation.MOTION_SENSOR_2 -> R.string.shop_equipment_motionsensor_data_info_2
        EquipmentTierInformation.MOTION_SENSOR_3 -> R.string.shop_equipment_motionsensor_data_info_3
        EquipmentTierInformation.SOUND_RECORDER_1 -> R.string.shop_equipment_soundrecorder_data_info_1
        EquipmentTierInformation.SOUND_RECORDER_2 -> R.string.shop_equipment_soundrecorder_data_info_2
        EquipmentTierInformation.SOUND_RECORDER_3 -> R.string.shop_equipment_soundrecorder_data_info_3
        EquipmentTierInformation.SOUND_SENSOR_1 -> R.string.shop_equipment_soundsensor_data_info_1
        EquipmentTierInformation.SOUND_SENSOR_2 -> R.string.shop_equipment_soundsensor_data_info_2
        EquipmentTierInformation.SOUND_SENSOR_3 -> R.string.shop_equipment_soundsensor_data_info_3
        EquipmentTierInformation.SANITY_MEDICATION_1 -> R.string.shop_equipment_sanitymedication_data_info_1
        EquipmentTierInformation.SANITY_MEDICATION_2 -> R.string.shop_equipment_sanitymedication_data_info_2
        EquipmentTierInformation.SANITY_MEDICATION_3 -> R.string.shop_equipment_sanitymedication_data_info_3
        EquipmentTierInformation.GHOST_WRITING_BOOK_1 -> R.string.shop_equipment_ghostwritingbook_data_info_1
        EquipmentTierInformation.GHOST_WRITING_BOOK_2 -> R.string.shop_equipment_ghostwritingbook_data_info_2
        EquipmentTierInformation.GHOST_WRITING_BOOK_3 -> R.string.shop_equipment_ghostwritingbook_data_info_3
        EquipmentTierInformation.PARABOLIC_MICROPHONE_1 -> R.string.shop_equipment_parabolicmicrophone_data_info_1
        EquipmentTierInformation.PARABOLIC_MICROPHONE_2 -> R.string.shop_equipment_parabolicmicrophone_data_info_2
        EquipmentTierInformation.PARABOLIC_MICROPHONE_3 -> R.string.shop_equipment_parabolicmicrophone_data_info_3
        EquipmentTierInformation.HEAD_GEAR_1 -> R.string.shop_equipment_headgear_data_info_1
        EquipmentTierInformation.HEAD_GEAR_2 -> R.string.shop_equipment_headgear_data_info_2
        EquipmentTierInformation.HEAD_GEAR_3 -> R.string.shop_equipment_headgear_data_info_3
    }

@StringRes fun EquipmentTierFlavorText.toStringResource(): Int =
    when (this) {
        EquipmentTierFlavorText.DOTS_1 -> R.string.shop_equipment_dots_data_flavortext_1
        EquipmentTierFlavorText.DOTS_2 -> R.string.shop_equipment_dots_data_flavortext_2
        EquipmentTierFlavorText.DOTS_3 -> R.string.shop_equipment_dots_data_flavortext_3
        EquipmentTierFlavorText.EMF_1 -> R.string.shop_equipment_emf_data_flavortext_1
        EquipmentTierFlavorText.EMF_2 -> R.string.shop_equipment_emf_data_flavortext_2
        EquipmentTierFlavorText.EMF_3 -> R.string.shop_equipment_emf_data_flavortext_3
        EquipmentTierFlavorText.FLASHLIGHT_1 -> R.string.shop_equipment_flashlight_data_flavortext_1
        EquipmentTierFlavorText.FLASHLIGHT_2 -> R.string.shop_equipment_flashlight_data_flavortext_2
        EquipmentTierFlavorText.FLASHLIGHT_3 -> R.string.shop_equipment_flashlight_data_flavortext_3
        EquipmentTierFlavorText.PHOTO_CAMERA_1 -> R.string.shop_equipment_photocamera_data_flavortext_1
        EquipmentTierFlavorText.PHOTO_CAMERA_2 -> R.string.shop_equipment_photocamera_data_flavortext_2
        EquipmentTierFlavorText.PHOTO_CAMERA_3 -> R.string.shop_equipment_photocamera_data_flavortext_3
        EquipmentTierFlavorText.IGNITER_1 -> R.string.shop_equipment_igniter_data_flavortext_1
        EquipmentTierFlavorText.IGNITER_2 -> R.string.shop_equipment_igniter_data_flavortext_2
        EquipmentTierFlavorText.IGNITER_3 -> R.string.shop_equipment_igniter_data_flavortext_3
        EquipmentTierFlavorText.FIRELIGHT_1 -> R.string.shop_equipment_firelight_data_flavortext_1
        EquipmentTierFlavorText.FIRELIGHT_2 -> R.string.shop_equipment_firelight_data_flavortext_2
        EquipmentTierFlavorText.FIRELIGHT_3 -> R.string.shop_equipment_firelight_data_flavortext_3
        EquipmentTierFlavorText.UV_LIGHT_1 -> R.string.shop_equipment_uvlight_data_flavortext_2
        EquipmentTierFlavorText.UV_LIGHT_2 -> R.string.shop_equipment_uvlight_data_flavortext_1
        EquipmentTierFlavorText.UV_LIGHT_3 -> R.string.shop_equipment_uvlight_data_flavortext_3
        EquipmentTierFlavorText.CRUCIFIX_1 -> R.string.shop_equipment_crucifix_data_flavortext_1
        EquipmentTierFlavorText.CRUCIFIX_2 -> R.string.shop_equipment_crucifix_data_flavortext_2
        EquipmentTierFlavorText.CRUCIFIX_3 -> R.string.shop_equipment_crucifix_data_flavortext_3
        EquipmentTierFlavorText.VIDEO_CAMERA_1 -> R.string.shop_equipment_videocamera_data_flavortext_1
        EquipmentTierFlavorText.VIDEO_CAMERA_2 -> R.string.shop_equipment_videocamera_data_flavortext_2
        EquipmentTierFlavorText.VIDEO_CAMERA_3 -> R.string.shop_equipment_videocamera_data_flavortext_3
        EquipmentTierFlavorText.SPIRIT_BOX_1 -> R.string.shop_equipment_spiritbox_data_flavortext_1
        EquipmentTierFlavorText.SPIRIT_BOX_2 -> R.string.shop_equipment_spiritbox_data_flavortext_2
        EquipmentTierFlavorText.SPIRIT_BOX_3 -> R.string.shop_equipment_spiritbox_data_flavortext_3
        EquipmentTierFlavorText.THERMOMETER_1 -> R.string.shop_equipment_thermometer_data_flavortext_1
        EquipmentTierFlavorText.THERMOMETER_2 -> R.string.shop_equipment_thermometer_data_flavortext_2
        EquipmentTierFlavorText.THERMOMETER_3 -> R.string.shop_equipment_thermometer_data_flavortext_3
        EquipmentTierFlavorText.SALT_1 -> R.string.shop_equipment_salt_data_flavortext_1
        EquipmentTierFlavorText.SALT_2 -> R.string.shop_equipment_salt_data_flavortext_2
        EquipmentTierFlavorText.SALT_3 -> R.string.shop_equipment_salt_data_flavortext_3
        EquipmentTierFlavorText.INCENSE_1 -> R.string.shop_equipment_incense_data_flavortext_1
        EquipmentTierFlavorText.INCENSE_2 -> R.string.shop_equipment_incense_data_flavortext_2
        EquipmentTierFlavorText.INCENSE_3 -> R.string.shop_equipment_incense_data_flavortext_3
        EquipmentTierFlavorText.TRIPOD_1 -> R.string.shop_equipment_tripod_data_flavortext_1
        EquipmentTierFlavorText.TRIPOD_2 -> R.string.shop_equipment_tripod_data_flavortext_2
        EquipmentTierFlavorText.TRIPOD_3 -> R.string.shop_equipment_tripod_data_flavortext_3
        EquipmentTierFlavorText.MOTION_SENSOR_1 -> R.string.shop_equipment_motionsensor_data_flavortext_1
        EquipmentTierFlavorText.MOTION_SENSOR_2 -> R.string.shop_equipment_motionsensor_data_flavortext_2
        EquipmentTierFlavorText.MOTION_SENSOR_3 -> R.string.shop_equipment_motionsensor_data_flavortext_3
        EquipmentTierFlavorText.SOUND_RECORDER_1 -> R.string.shop_equipment_soundrecorder_data_flavortext_1
        EquipmentTierFlavorText.SOUND_RECORDER_2 -> R.string.shop_equipment_soundrecorder_data_flavortext_2
        EquipmentTierFlavorText.SOUND_RECORDER_3 -> R.string.shop_equipment_soundrecorder_data_flavortext_3
        EquipmentTierFlavorText.SOUND_SENSOR_1 -> R.string.shop_equipment_soundsensor_data_flavortext_1
        EquipmentTierFlavorText.SOUND_SENSOR_2 -> R.string.shop_equipment_soundsensor_data_flavortext_2
        EquipmentTierFlavorText.SOUND_SENSOR_3 -> R.string.shop_equipment_soundsensor_data_flavortext_3
        EquipmentTierFlavorText.SANITY_MEDICATION_1 -> R.string.shop_equipment_sanitymedication_data_flavortext_1
        EquipmentTierFlavorText.SANITY_MEDICATION_2 -> R.string.shop_equipment_sanitymedication_data_flavortext_2
        EquipmentTierFlavorText.SANITY_MEDICATION_3 -> R.string.shop_equipment_sanitymedication_data_flavortext_3
        EquipmentTierFlavorText.GHOST_WRITING_BOOK_1 -> R.string.shop_equipment_ghostwritingbook_data_flavortext_1
        EquipmentTierFlavorText.GHOST_WRITING_BOOK_2 -> R.string.shop_equipment_ghostwritingbook_data_flavortext_2
        EquipmentTierFlavorText.GHOST_WRITING_BOOK_3 -> R.string.shop_equipment_ghostwritingbook_data_flavortext_3
        EquipmentTierFlavorText.PARABOLIC_MICROPHONE_1 -> R.string.shop_equipment_parabolicmicrophone_data_flavortext_1
        EquipmentTierFlavorText.PARABOLIC_MICROPHONE_2 -> R.string.shop_equipment_parabolicmicrophone_data_flavortext_2
        EquipmentTierFlavorText.PARABOLIC_MICROPHONE_3 -> R.string.shop_equipment_parabolicmicrophone_data_flavortext_3
        EquipmentTierFlavorText.HEAD_GEAR_1 -> R.string.shop_equipment_headgear_data_flavortext_1
        EquipmentTierFlavorText.HEAD_GEAR_2 -> R.string.shop_equipment_headgear_data_flavortext_2
        EquipmentTierFlavorText.HEAD_GEAR_3 -> R.string.shop_equipment_headgear_data_flavortext_3
    }

@IntegerRes fun EquipmentBuyCost.toIntegerResource(): Int =
    when (this) {
        EquipmentBuyCost.DOTS -> BuyCost.COST_65.toIntegerResource()
        EquipmentBuyCost.EMF -> BuyCost.COST_45.toIntegerResource()
        EquipmentBuyCost.UV_LIGHT -> BuyCost.COST_35.toIntegerResource()
        EquipmentBuyCost.THERMOMETER -> BuyCost.COST_30.toIntegerResource()
        EquipmentBuyCost.VIDEO_CAMERA -> BuyCost.COST_50.toIntegerResource()
        EquipmentBuyCost.GHOST_WRITING_BOOK -> BuyCost.COST_40.toIntegerResource()
        EquipmentBuyCost.SPIRIT_BOX -> BuyCost.COST_50.toIntegerResource()
        EquipmentBuyCost.FLASHLIGHT -> BuyCost.COST_30.toIntegerResource()
        EquipmentBuyCost.PHOTO_CAMERA -> BuyCost.COST_40.toIntegerResource()
        EquipmentBuyCost.IGNITER -> BuyCost.COST_10.toIntegerResource()
        EquipmentBuyCost.FIRELIGHT -> BuyCost.COST_15.toIntegerResource()
        EquipmentBuyCost.CRUCIFIX -> BuyCost.COST_30.toIntegerResource()
        EquipmentBuyCost.SALT -> BuyCost.COST_15.toIntegerResource()
        EquipmentBuyCost.INCENSE -> BuyCost.COST_15.toIntegerResource()
        EquipmentBuyCost.TRIPOD -> BuyCost.COST_25.toIntegerResource()
        EquipmentBuyCost.MOTION_SENSOR -> BuyCost.COST_100.toIntegerResource()
        EquipmentBuyCost.SOUND_RECORDER -> BuyCost.COST_30.toIntegerResource()
        EquipmentBuyCost.SOUND_SENSOR -> BuyCost.COST_80.toIntegerResource()
        EquipmentBuyCost.SANITY_MEDICATION -> BuyCost.COST_20.toIntegerResource()
        EquipmentBuyCost.PARABOLIC_MICROPHONE -> BuyCost.COST_50.toIntegerResource()
        EquipmentBuyCost.HEAD_GEAR -> BuyCost.COST_60.toIntegerResource()
    }

@IntegerRes fun BuyCost.toIntegerResource(): Int =
    when (this) {
        BuyCost.COST_10 -> R.integer.equipment_requirement_buycost_10
        BuyCost.COST_15 -> R.integer.equipment_requirement_buycost_15
        BuyCost.COST_20 -> R.integer.equipment_requirement_buycost_20
        BuyCost.COST_25 -> R.integer.equipment_requirement_buycost_25
        BuyCost.COST_30 -> R.integer.equipment_requirement_buycost_30
        BuyCost.COST_35 -> R.integer.equipment_requirement_buycost_35
        BuyCost.COST_40 -> R.integer.equipment_requirement_buycost_40
        BuyCost.COST_45 -> R.integer.equipment_requirement_buycost_45
        BuyCost.COST_50 -> R.integer.equipment_requirement_buycost_50
        BuyCost.COST_60 -> R.integer.equipment_requirement_buycost_60
        BuyCost.COST_65 -> R.integer.equipment_requirement_buycost_65
        BuyCost.COST_80 -> R.integer.equipment_requirement_buycost_80
        BuyCost.COST_100 -> R.integer.equipment_requirement_buycost_100
    }


@IntegerRes fun EquipmentUpgradeCost.toIntegerResource(): Int =
    when (this) {
        EquipmentUpgradeCost.COST_0 -> R.integer.equipment_requirement_upgradecost_0
        EquipmentUpgradeCost.COST_500 -> R.integer.equipment_requirement_upgradecost_500
        EquipmentUpgradeCost.COST_750 -> R.integer.equipment_requirement_upgradecost_750
        EquipmentUpgradeCost.COST_1500 -> R.integer.equipment_requirement_upgradecost_1500
        EquipmentUpgradeCost.COST_2000 -> R.integer.equipment_requirement_upgradecost_2000
        EquipmentUpgradeCost.COST_2500 -> R.integer.equipment_requirement_upgradecost_2500
        EquipmentUpgradeCost.COST_3000 -> R.integer.equipment_requirement_upgradecost_3000
        EquipmentUpgradeCost.COST_3500 -> R.integer.equipment_requirement_upgradecost_3500
        EquipmentUpgradeCost.COST_4000 -> R.integer.equipment_requirement_upgradecost_4000
        EquipmentUpgradeCost.COST_4500 -> R.integer.equipment_requirement_upgradecost_4500
        EquipmentUpgradeCost.COST_5000 -> R.integer.equipment_requirement_upgradecost_5000
        EquipmentUpgradeCost.COST_8000 -> R.integer.equipment_requirement_upgradecost_8000
        EquipmentUpgradeCost.COST_10000 -> R.integer.equipment_requirement_upgradecost_10000
        EquipmentUpgradeCost.COST_15000 -> R.integer.equipment_requirement_upgradecost_15000
        EquipmentUpgradeCost.COST_20000 -> R.integer.equipment_requirement_upgradecost_20000
    }

@IntegerRes fun EquipmentUnlockLevel.toIntegerResource(): Int =
    when (this) {
        EquipmentUnlockLevel.LEVEL_0 -> R.integer.equipment_requirement_level_0
        EquipmentUnlockLevel.LEVEL_2 -> R.integer.equipment_requirement_level_2
        EquipmentUnlockLevel.LEVEL_3 -> R.integer.equipment_requirement_level_3
        EquipmentUnlockLevel.LEVEL_4 -> R.integer.equipment_requirement_level_4
        EquipmentUnlockLevel.LEVEL_5 -> R.integer.equipment_requirement_level_5
        EquipmentUnlockLevel.LEVEL_7 -> R.integer.equipment_requirement_level_7
        EquipmentUnlockLevel.LEVEL_8 -> R.integer.equipment_requirement_level_8
        EquipmentUnlockLevel.LEVEL_9 -> R.integer.equipment_requirement_level_9
        EquipmentUnlockLevel.LEVEL_10 -> R.integer.equipment_requirement_level_10
        EquipmentUnlockLevel.LEVEL_11 -> R.integer.equipment_requirement_level_11
        EquipmentUnlockLevel.LEVEL_12 -> R.integer.equipment_requirement_level_12
        EquipmentUnlockLevel.LEVEL_13 -> R.integer.equipment_requirement_level_13
        EquipmentUnlockLevel.LEVEL_14 -> R.integer.equipment_requirement_level_14
        EquipmentUnlockLevel.LEVEL_18 -> R.integer.equipment_requirement_level_18
        EquipmentUnlockLevel.LEVEL_19 -> R.integer.equipment_requirement_level_19
        EquipmentUnlockLevel.LEVEL_20 -> R.integer.equipment_requirement_level_20
        EquipmentUnlockLevel.LEVEL_21 -> R.integer.equipment_requirement_level_21
        EquipmentUnlockLevel.LEVEL_23 -> R.integer.equipment_requirement_level_23
        EquipmentUnlockLevel.LEVEL_25 -> R.integer.equipment_requirement_level_25
        EquipmentUnlockLevel.LEVEL_27 -> R.integer.equipment_requirement_level_27
        EquipmentUnlockLevel.LEVEL_29 -> R.integer.equipment_requirement_level_29
        EquipmentUnlockLevel.LEVEL_31 -> R.integer.equipment_requirement_level_31
        EquipmentUnlockLevel.LEVEL_32 -> R.integer.equipment_requirement_level_32
        EquipmentUnlockLevel.LEVEL_33 -> R.integer.equipment_requirement_level_33
        EquipmentUnlockLevel.LEVEL_34 -> R.integer.equipment_requirement_level_34
        EquipmentUnlockLevel.LEVEL_35 -> R.integer.equipment_requirement_level_35
        EquipmentUnlockLevel.LEVEL_36 -> R.integer.equipment_requirement_level_36
        EquipmentUnlockLevel.LEVEL_37 -> R.integer.equipment_requirement_level_37
        EquipmentUnlockLevel.LEVEL_39 -> R.integer.equipment_requirement_level_39
        EquipmentUnlockLevel.LEVEL_41 -> R.integer.equipment_requirement_level_41
        EquipmentUnlockLevel.LEVEL_42 -> R.integer.equipment_requirement_level_42
        EquipmentUnlockLevel.LEVEL_43 -> R.integer.equipment_requirement_level_43
        EquipmentUnlockLevel.LEVEL_45 -> R.integer.equipment_requirement_level_45
        EquipmentUnlockLevel.LEVEL_46 -> R.integer.equipment_requirement_level_46
        EquipmentUnlockLevel.LEVEL_47 -> R.integer.equipment_requirement_level_47
        EquipmentUnlockLevel.LEVEL_49 -> R.integer.equipment_requirement_level_49
        EquipmentUnlockLevel.LEVEL_52 -> R.integer.equipment_requirement_level_52
        EquipmentUnlockLevel.LEVEL_54 -> R.integer.equipment_requirement_level_54
        EquipmentUnlockLevel.LEVEL_55 -> R.integer.equipment_requirement_level_55
        EquipmentUnlockLevel.LEVEL_56 -> R.integer.equipment_requirement_level_56
        EquipmentUnlockLevel.LEVEL_57 -> R.integer.equipment_requirement_level_57
        EquipmentUnlockLevel.LEVEL_58 -> R.integer.equipment_requirement_level_58
        EquipmentUnlockLevel.LEVEL_60 -> R.integer.equipment_requirement_level_60
        EquipmentUnlockLevel.LEVEL_61 -> R.integer.equipment_requirement_level_61
        EquipmentUnlockLevel.LEVEL_62 -> R.integer.equipment_requirement_level_62
        EquipmentUnlockLevel.LEVEL_63 -> R.integer.equipment_requirement_level_63
        EquipmentUnlockLevel.LEVEL_64 -> R.integer.equipment_requirement_level_64
        EquipmentUnlockLevel.LEVEL_65 -> R.integer.equipment_requirement_level_65
        EquipmentUnlockLevel.LEVEL_68 -> R.integer.equipment_requirement_level_68
        EquipmentUnlockLevel.LEVEL_70 -> R.integer.equipment_requirement_level_70
        EquipmentUnlockLevel.LEVEL_72 -> R.integer.equipment_requirement_level_72
        EquipmentUnlockLevel.LEVEL_74 -> R.integer.equipment_requirement_level_74
        EquipmentUnlockLevel.LEVEL_75 -> R.integer.equipment_requirement_level_75
        EquipmentUnlockLevel.LEVEL_77 -> R.integer.equipment_requirement_level_77
        EquipmentUnlockLevel.LEVEL_79 -> R.integer.equipment_requirement_level_79
        EquipmentUnlockLevel.LEVEL_80 -> R.integer.equipment_requirement_level_80
        EquipmentUnlockLevel.LEVEL_82 -> R.integer.equipment_requirement_level_82
        EquipmentUnlockLevel.LEVEL_85 -> R.integer.equipment_requirement_level_85
        EquipmentUnlockLevel.LEVEL_90 -> R.integer.equipment_requirement_level_90
    }
